# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1deCo8b8H4Ex8lSyAQKbTQUAgIM9xbl4t
"""

import math


# Function to print the board
def print_board(board):

    for row in board:
        print(" | ".join(row))
        print("-" * 9)


# Function to check winner
def check_winner(board, player):

    # Check rows
    for row in board:
        if all(cell == player for cell in row):
            return True

    # Check columns
    for col in range(3):
        if all(board[row][col] == player for row in range(3)):
            return True

    # Check diagonals
    if all(board[i][i] == player for i in range(3)):
        return True

    if all(board[i][2 - i] == player for i in range(3)):
        return True

    return False


# Function to check if board is full
def is_full(board):

    for row in board:
        for cell in row:
            if cell == " ":
                return False

    return True


# Alpha-Beta Pruning Algorithm
def alpha_beta(board, depth, is_maximizing, alpha, beta):

    # Terminal states
    if check_winner(board, "O"):
        return 1

    if check_winner(board, "X"):
        return -1

    if is_full(board):
        return 0

    # Maximizing player (Computer)
    if is_maximizing:

        best_score = -math.inf

        for i in range(3):
            for j in range(3):

                if board[i][j] == " ":

                    board[i][j] = "O"

                    score = alpha_beta(
                        board,
                        depth + 1,
                        False,
                        alpha,
                        beta
                    )

                    board[i][j] = " "

                    best_score = max(best_score, score)

                    alpha = max(alpha, best_score)

                    # Beta Cutoff
                    if beta <= alpha:
                        break

        return best_score

    # Minimizing player (Human)
    else:

        best_score = math.inf

        for i in range(3):
            for j in range(3):

                if board[i][j] == " ":

                    board[i][j] = "X"

                    score = alpha_beta(
                        board,
                        depth + 1,
                        True,
                        alpha,
                        beta
                    )

                    board[i][j] = " "

                    best_score = min(best_score, score)

                    beta = min(beta, best_score)

                    # Alpha Cutoff
                    if beta <= alpha:
                        break

        return best_score


# Function to find best move for AI
def best_move(board):

    best_score = -math.inf
    move = (-1, -1)

    for i in range(3):
        for j in range(3):

            if board[i][j] == " ":

                board[i][j] = "O"

                score = alpha_beta(
                    board,
                    0,
                    False,
                    -math.inf,
                    math.inf
                )

                board[i][j] = " "

                if score > best_score:
                    best_score = score
                    move = (i, j)

    return move


# Main Game Function
def play_game():

    # Empty board
    board = [
        [" ", " ", " "],
        [" ", " ", " "],
        [" ", " ", " "]
    ]

    print("===== TIC TAC TOE =====")
    print("You are X")
    print("Computer is O")
    print()

    while True:

        # Display board
        print_board(board)

        # Human Move
        while True:

            try:

                row = int(input("Enter row (0-2): "))
                col = int(input("Enter column (0-2): "))

                # Check valid range
                if row < 0 or row > 2 or col < 0 or col > 2:
                    print("Invalid input! Row and column must be between 0 and 2.")
                    continue

                # Check empty cell
                if board[row][col] != " ":
                    print("Cell already occupied! Try again.")
                    continue

                break

            except ValueError:
                print("Please enter numbers only!")

        # Place player's move
        board[row][col] = "X"

        # Check if player wins
        if check_winner(board, "X"):

            print_board(board)
            print("You Win!")
            break

        # Check draw
        if is_full(board):

            print_board(board)
            print("Game Draw!")
            break

        # Computer Move
        print("\nComputer is making a move...\n")

        ai_row, ai_col = best_move(board)

        board[ai_row][ai_col] = "O"

        # Check if computer wins
        if check_winner(board, "O"):

            print_board(board)
            print("Computer Wins!")
            break

        # Check draw
        if is_full(board):

            print_board(board)
            print("Game Draw!")
            break


# Run the Game
play_game()